//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_ogrenci_kayit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int OgrID { get; set; }
        public string OgrAD { get; set; }
        public string OgrSoyad { get; set; }
        public string OgrMail { get; set; }
        public string OgrFotograf { get; set; }
        public string OgrAdres { get; set; }
    }
}
